### ISSUE TITLE
Issue setting dark theme

### ISSUE THREAD

**Issue by MrFlyingToasterman** [Pascal3366/QuiEmu#1]
I guess the program dosent create a folder in ".config/".
I tried the theme function before i created a machine.

The directory QuiEmu dosent exist in my ".config/".

Stacktrace:
`QIODevice::read (QFile, "/home/dmusiolik/.config/QuiEmu/appearance.json"): device not open`

**Comment by Pascal3366** [comment]
Fixed it by creating the needed directory on each program start if its not existant.
