### ISSUE TITLE
Error creating new mashine

### ISSUE THREAD

**Issue by MrFlyingToasterman** [Pascal3366/QuiEmu#3]
I could not create an new mashine. I followed the mashinesetup and ended up with this stacktrace:

```
QIODevice::write (QFile, "/home/dmusiolik/.config/QuiEmu/Machines/Lunar GNU/Linux.json"): device not open
QIODevice::read (QFile, "/home/pascal/.config/QuiEmu/Machines/.json"): device not open

```

Maybe its because i named my mashine "Lunar GNU/Linux". 
I think its possible that the whitespace or the Slash is the problem.

**Comment by Pascal3366** [comment]
fixed
